### ISSUE TITLE
I don't get the delete e-mail link in the mails to me? how do i delete the email adresses

### ISSUE THREAD

**Issue by RiimoH** [hintofbasil/Shadowmail#33]
also i get a huge flood of spam recently. Just me?

**Comment by hintofbasil** [comment]
Hi RiimoH,

I've been working on improving the deliverability of the emails.  This is likely the cause for the upswing in emails received.

Unfortunately this broke the attaching of the delete email text.  I hope to get a fix out in the next few days.  Until then you can delete the addresses at https://shadowmail.co.uk/request_delete/.

**Comment by hintofbasil** [comment]
Re-add the footer: https://github.com/hintofbasil/Shadowmail/pull/37

**Comment by hintofbasil** [comment]
Fix deployed and working.

**Comment by hintofbasil** [comment]
Re-opening as this doesn't handle base64 encoded emails

**Comment by hintofbasil** [comment]
Fix the base64 issue: https://github.com/hintofbasil/Shadowmail/pull/39

**Comment by hintofbasil** [comment]
Build the correct delete link when the To address contains a name: https://github.com/hintofbasil/Shadowmail/pull/40

**Comment by hintofbasil** [comment]
Closing.  Issue seems to be fixed.
